### ISSUE TITLE
Enable generation of LEMMA models from OpenAPI files

### ISSUE THREAD

**Issue by josor001** [SeelabFhdo/lemma#33]
Many teams in practice use OpenAPI to document their RESTful interfaces. Hence, it would be great to add a new button/menu item and provide a mechanism for OpenAPI-2-LEMMA.
OpenAPI descs probably contain domain data (schemas in openapi) and service information (api desc in openapi).

**Comment by frademacher** [comment]
cf. https://github.com/SeelabFhdo/lemma/pull/55#issuecomment-1211640356

**Comment by frademacher** [comment]
With the merge of the OpenAPI transformation (cf. PR https://github.com/SeelabFhdo/lemma/pull/65), we can now derive LEMMA models from OpenAPI. Would be nice to turn this feature into a bidirectional transformation that also supports LEMMA-to-OpenAPI in the future.
